/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author fredaum
 */
public class Calcula extends javax.swing.JFrame {

    /**
     * Creates new form Calcula
     */
    public Calcula() {
        initComponents();
    }
    
    
    Double peso, gravidade;
    String planeta;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rMercurio = new javax.swing.JRadioButton();
        rVenus = new javax.swing.JRadioButton();
        rMarte = new javax.swing.JRadioButton();
        rJupiter = new javax.swing.JRadioButton();
        rSaturno = new javax.swing.JRadioButton();
        rUrano = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Balança");
        setResizable(false);

        jLabel1.setText("Peso na Terra (kg):");

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular Peso");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione o Planeta:");

        buttonGroup1.add(rMercurio);
        rMercurio.setText("Mercúrio");

        buttonGroup1.add(rVenus);
        rVenus.setText("Vênus");

        buttonGroup1.add(rMarte);
        rMarte.setText("Marte");

        buttonGroup1.add(rJupiter);
        rJupiter.setText("Júpiter");

        buttonGroup1.add(rSaturno);
        rSaturno.setText("Saturno");

        buttonGroup1.add(rUrano);
        rUrano.setText("Urano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPeso))
                        .addGap(103, 103, 103)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rMercurio)
                            .addComponent(rVenus))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rJupiter)
                            .addComponent(rMarte))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSaturno)
                            .addComponent(rUrano))))
                .addGap(24, 36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPeso))
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rMercurio)
                    .addComponent(rMarte)
                    .addComponent(rSaturno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rVenus)
                    .addComponent(rJupiter)
                    .addComponent(rUrano))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
        peso = Double.parseDouble(txtPeso.getText());
    }//GEN-LAST:event_txtPesoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try {
            if (rMercurio.isSelected()){
                gravidade = 0.37;
                planeta = "Mercúrio";
            }
            else if (rVenus.isSelected()){
                gravidade = 0.88;
                planeta = "Vênus";
            }
            else if (rMarte.isSelected()){
                gravidade = 0.38;
                planeta = "Marte";
            }
            else if (rJupiter.isSelected()){
                gravidade = 2.64;
                planeta = "Júpiter";
            }
            else if (rSaturno.isSelected()){
                gravidade = 1.15;
                planeta = "Saturno";
            }
            else if (rUrano.isSelected()){
                gravidade = 1.17;
                planeta = "Urano";
            }
            else 
                ;
            
            DecimalFormat formatador = new DecimalFormat();
            formatador.setMaximumFractionDigits(2);
            JOptionPane.showMessageDialog(null, "O seu peso em " + planeta + " é: " + formatador.format(calculaPeso()) + " kg");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algum dado foi mal informado!", "Atenção" , 1);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed
    public double calculaPeso() {
        return peso * gravidade;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rJupiter;
    private javax.swing.JRadioButton rMarte;
    private javax.swing.JRadioButton rMercurio;
    private javax.swing.JRadioButton rSaturno;
    private javax.swing.JRadioButton rUrano;
    private javax.swing.JRadioButton rVenus;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
